In [8]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
#help(np.min)

In [10]:
#help(np.append)

In [11]:
i = 0
while i < 5:
    print(i)
    i = i+ 1

0
1
2
3
4


In [12]:
k_result = np.array([5462.29745234, 1684.9079503,  1329.59486715, 1035.49982654])
em_result = np.array([-1307.22343176, -1175.71486373, -1138.89152686, -1138.89104563])

In [13]:
def bic(n, d, K, LL):
    r = K + (K -1) + K*d
    val = LL - np.log(n) * r/2
    return val

In [14]:
n = 15
d = 2
K = 6
LL = -1207.121971
v = bic(n, d, K,LL)
v

-1238.2645483126755

In [15]:
n = 10
d = 2
K = 5
LL = -1447.747034
v = bic(n, d, K,LL)
v

-1469.6215923834434

In [16]:
ans = -1469.621592
val = (LL - ans)*2/np.log(n)
val

18.999999666945246

In [17]:
(LL - ans)

21.87455799999998

In [18]:
from scipy.special import logsumexp

In [19]:
a = np.arange(5)
logsumexp(a)

4.451914395937593

In [20]:
a1 = np.array([[2,0,0,0,5],
               [1, 2, 0, 3, 0]])
b1 = np.array([[2,4,5,8,9],
               [1,2,3,5,6]])
num, d = a1.shape
cu = []
for n in np.arange(num):
    flag = [i for i in np.arange(d) if a1[n,i] != 0]
    cu.append(flag)
#map_flag = map_flag.reshape((num, d))
print(cu)
for n in np.arange(num):
    a = a1[n, cu[n]]
    b = b1[n, cu[n]]
    print(a,b)

[[0, 4], [0, 1, 3]]
[2 5] [2 9]
[1 2 3] [1 2 5]


In [21]:
a1 = np.array([[2,0,3,0,5],
               [1, 2, 0, 3, 0]])
b1 = np.array([[2,4,5,8,9],
               [1,2,3,5,6]])
num, d = a1.shape
map_flag = np.array([i for i in np.arange(d) if a1[0,i] != 0]).reshape(1,-1)
map_flag, map_flag.shape

(array([[0, 2, 4]]), (1, 3))

In [22]:
c1 = np.array([[1,2,3],[2,3]])
c1

array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [23]:
c1[1]

[2, 3]

In [24]:
c = []
c1 = [1,2]
c2 = [4,5,6]
c.append(c1)
c.append(c2)
cn = np.array(c)
cn

array([list([1, 2]), list([4, 5, 6])], dtype=object)

In [25]:
w = []
w1 = [1,2,3]
w2 = [4,5,6]
w.append(w1)
w.append(w2)
nw = np.array(w)
nw

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
w = []
len(w)

0

In [30]:
t1 = False
t2 = True
t1 * 2, t2 * 5

(0, 5)

In [33]:
t1 = np.array(np.arange(1,13)).reshape(3,4)
t1[0, [1,3]] = 10
t1

array([[ 1, 10,  3, 10],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
alist = [[1,2],[4,5,6]]
len(alist)

2

In [37]:
#help(np.reshape)

In [44]:
u = np.array(np.arange(1,13)).reshape(3,4)
v = np.array(np.arange(101, 113)).reshape(3,4)
u,v

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112]]))

In [45]:
u[1] = v[1]

In [46]:
u,v

(array([[  1,   2,   3,   4],
        [105, 106, 107, 108],
        [  9,  10,  11,  12]]),
 array([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112]]))

In [ ]:
Mu: [[0.41077387 0.63624413]
 [0.53764366 0.59028913]
 [0.49197915 0.60967321]
 [0.48802184 0.60538121]
 [0.58135134 0.64956631]
 [0.42757693 0.55222412]
 [0.49924273 0.59304358]
 [0.44226616 0.60200728]
 [0.54203216 0.66760912]]
Var: [0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25]
P: [0.11384329 0.09264076 0.09886894 0.12439608 0.09727906 0.1233966
 0.11249143 0.10730585 0.12977798]