In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#help(np.min)

In [3]:
#help(np.append)

In [4]:
i = 0
while i < 5:
    print(i)
    i = i+ 1

0
1
2
3
4


In [5]:
k_result = np.array([5462.29745234, 1684.9079503,  1329.59486715, 1035.49982654])
em_result = np.array([-1307.22343176, -1175.71486373, -1138.89152686, -1138.89104563])

In [6]:
def bic(n, d, K, LL):
    r = K + (K -1) + K*d
    val = LL - np.log(n) * r/2
    return val

In [7]:
n = 15
d = 2
K = 6
LL = -1207.121971
v = bic(n, d, K,LL)
v

-1238.2645483126755

In [8]:
n = 10
d = 2
K = 5
LL = -1447.747034
v = bic(n, d, K,LL)
v

-1469.6215923834434

In [9]:
ans = -1469.621592
val = (LL - ans)*2/np.log(n)
val

18.999999666945246

In [10]:
(LL - ans)

21.87455799999998

In [11]:
from scipy.special import logsumexp

In [12]:
a = np.arange(5)
logsumexp(a)

4.451914395937593

In [13]:
a1 = np.array([[2,0,0,0,5],
               [1, 2, 0, 3, 0]])
b1 = np.array([[2,4,5,8,9],
               [1,2,3,5,6]])
num, d = a1.shape
cu = []
for n in np.arange(num):
    flag = [i for i in np.arange(d) if a1[n,i] != 0]
    cu.append(flag)
#map_flag = map_flag.reshape((num, d))
print(cu)
for n in np.arange(num):
    a = a1[n, cu[n]]
    b = b1[n, cu[n]]
    print(a,b)

[[0, 4], [0, 1, 3]]
[2 5] [2 9]
[1 2 3] [1 2 5]


In [14]:
a1 = np.array([[2,0,3,0,5],
               [1, 2, 0, 3, 0]])
b1 = np.array([[2,4,5,8,9],
               [1,2,3,5,6]])
num, d = a1.shape
map_flag = np.array([i for i in np.arange(d) if a1[0,i] != 0]).reshape(1,-1)
map_flag, map_flag.shape

(array([[0, 2, 4]]), (1, 3))

In [15]:
c1 = np.array([[1,2,3],[2,3]])
c1

array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [16]:
c1[1]

[2, 3]

In [17]:
c = []
c1 = [1,2]
c2 = [4,5,6]
c.append(c1)
c.append(c2)
cn = np.array(c)
cn

array([list([1, 2]), list([4, 5, 6])], dtype=object)

In [18]:
w = []
w1 = [1,2,3]
w2 = [4,5,6]
w.append(w1)
w.append(w2)
nw = np.array(w)
nw

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
w = []
len(w)

0

In [20]:
t1 = False
t2 = True
t1 * 2, t2 * 5

(0, 5)

In [21]:
t1 = np.array(np.arange(1,13)).reshape(3,4)
t1[0, [1,3]] = 10
t1

array([[ 1, 10,  3, 10],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
alist = [[1,2],[4,5,6]]
len(alist)

2

In [23]:
#help(np.reshape)

In [24]:
u = np.array(np.arange(1,13)).reshape(3,4)
v = np.array(np.arange(101, 113)).reshape(3,4)
u,v

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112]]))

In [25]:
u[1] = v[1]

In [26]:
u,v

(array([[  1,   2,   3,   4],
        [105, 106, 107, 108],
        [  9,  10,  11,  12]]),
 array([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112]]))

In [27]:
np.exp(-1.7917)

0.16667657849939743

In [28]:
np.log(1e-10)

-23.025850929940457

In [29]:
nn = [0.00, 0.00, 0.00, 0.00]
if (np.sum(nn) <1e-6 or (np.sum(nn) < 1e-4)):
    nn = [0.25,0.25,0.25,0.25]
nn

[0.25, 0.25, 0.25, 0.25]

In [30]:
np.log(0.25)

-1.3862943611198906

In [31]:
4.001247 * 0.8351 + 3.5242 * 0.126 + 0.008 * 4.5552 + 0.0307*3.99998


3.9447315557

In [32]:
a1 = np.arange(1,13).reshape(3,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a1[1,[1,2]] = [100,200]
a1

array([[  1,   2,   3,   4],
       [  5, 100, 200,   8],
       [  9,  10,  11,  12]])

In [34]:
b1 = np.copy(a1)
a1[1,1] = 1000
a1, b1

(array([[   1,    2,    3,    4],
        [   5, 1000,  200,    8],
        [   9,   10,   11,   12]]),
 array([[  1,   2,   3,   4],
        [  5, 100, 200,   8],
        [  9,  10,  11,  12]]))

In [35]:
d1 = b1[:,[0,1,2]]
d1

array([[  1,   2,   3],
       [  5, 100, 200],
       [  9,  10,  11]])

In [36]:
d1 = b1[:,[0,1,2]]
c1 = np.matmul(d1[2:,],a1)
a1,d1,c1

(array([[   1,    2,    3,    4],
        [   5, 1000,  200,    8],
        [   9,   10,   11,   12]]),
 array([[  1,   2,   3],
        [  5, 100, 200],
        [  9,  10,  11]]),
 array([[  158, 10128,  2148,   248]]))

In [38]:
0.4857973 * -0.45998405 + 0.5142027 * 0.3064

-0.06590730225306499

In [39]:
1e-16 + 0.005


0.0050000000000001

In [40]:
X_pred:[[ 2.          4.          5.         ...  4.          2.
   4.        ]
 [ 1.          3.          4.         ...  3.         -0.06590646
   3.        ]
 [ 3.          5.         -0.314108   ...  3.          4.
   0.38493707]
 ...
 [ 5.          3.         -0.314108   ...  3.          5.
   4.        ]
 [ 2.          3.         -0.314108   ...  5.         -0.06590646
   0.38493707]
 [ 3.          0.06996183 -0.314108   ...  3.         -0.06590646
   3.        ]]

SyntaxError: invalid syntax (<ipython-input-40-7e8dd40a4680>, line 1)

In [41]:
loglikehood = 0.0
l_old = 0.0
np.abs(loglikehood - l_old) >= (10**-6 * np.abs(loglikehood) + 1e-16)

False

In [42]:
from scipy.stats import multivariate_normal as mnorm
from scipy.stats import norm

In [43]:
mu = np.array([2,4,5,5,0])
var = 5.93
x = np.array([2,5,3,0,0])

In [47]:
nn = np.array([mnorm.pdf(x[[0,1,2]], mean= mu[[0,1,2]],cov=var)])
nn

array([0.0028844])

In [48]:
-1.38529 + np.log(0.00288)

-7.235254984834283

In [50]:
cu = [0,1,2]
n1 = [norm.pdf(x[i], loc=mu[i], scale = np.sqrt(var)) for i in cu]
n1

[0.16382595909121891, 0.1505789614247414, 0.11692544519264575]

In [53]:
sum(np.log(n1))

-5.84843707933083

In [54]:
np.log(nn)

array([-5.84843708])

In [55]:
np.log(0.025779)

-3.6581950719829415

In [56]:
np.log(0.1129)

-2.1812528078265205

In [57]:
np.log(1e-16)

-36.841361487904734

In [59]:
np.log(np.e**-16)

-16.0

In [60]:
np.log(0+1e-16)

-36.841361487904734

In [61]:
np.log(0+1e-16)

-36.841361487904734