In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#help(np.min)

In [3]:
#help(np.append)

In [4]:
i = 0
while i < 5:
    print(i)
    i = i+ 1

0
1
2
3
4


In [5]:
k_result = np.array([5462.29745234, 1684.9079503,  1329.59486715, 1035.49982654])
em_result = np.array([-1307.22343176, -1175.71486373, -1138.89152686, -1138.89104563])

In [8]:
n = 15
d = 2
K = 6
LL = -1207.121971
v = bic(n, d, K,LL)
v

-1238.2645483126755

In [9]:
def bic(n, d, K, LL):
    r = K + (K -1) + K*d
    val = LL - np.log(n) * r/2
    return val

In [10]:
n = 10
d = 2
K = 5
LL = -1447.747034
v = bic(n, d, K,LL)
v

-1469.6215923834434

In [11]:
ans = -1469.621592
val = (LL - ans)*2/np.log(n)
val

18.999999666945246

In [12]:
(LL - ans)

21.87455799999998

In [43]:
from scipy.special import logsumexp

In [21]:
a = np.arange(5)
logsumexp(a)

4.451914395937593

In [83]:
a1 = np.array([[2,0,0,0,5],
               [1, 2, 0, 3, 0]])
b1 = np.array([[2,4,5,8,9],
               [1,2,3,5,6]])
num, d = a1.shape
cu = []
for n in np.arange(num):
    flag = [i for i in np.arange(d) if a1[n,i] != 0]
    cu.append(flag)
#map_flag = map_flag.reshape((num, d))
print(cu)
for n in np.arange(num):
    a = a1[n, cu[n]]
    b = b1[n, cu[n]]
    print(a,b)

[[0, 4], [0, 1, 3]]
[2 5] [2 9]
[1 2 3] [1 2 5]


In [56]:
a1 = np.array([[2,0,3,0,5],
               [1, 2, 0, 3, 0]])
b1 = np.array([[2,4,5,8,9],
               [1,2,3,5,6]])
num, d = a1.shape
map_flag = np.array([i for i in np.arange(d) if a1[0,i] != 0]).reshape(1,-1)
map_flag, map_flag.shape

(array([[0, 2, 4]]), (1, 3))

In [59]:
c1 = np.array([[1,2,3],[2,3]])
c1

array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [62]:
c1[1]

[2, 3]

In [79]:
c = []
c1 = [1,2]
c2 = [4,5,6]
c.append(c1)
c.append(c2)
cn = np.array(c)
cn

array([list([1, 2]), list([4, 5, 6])], dtype=object)

In [86]:
w = []
w1 = [1,2,3]
w2 = [4,5,6]
w.append(w1)
w.append(w2)
nw = np.array(w)
nw

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
w = []
len(w)

0