In [1]:
import torch
import numpy as np

In [4]:
x = np.array([[1,2],[3,4]])
x_tensor = torch.from_numpy(x)
x, x_tensor

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [6]:
x = torch.rand(3,4)
print(f"Device tensor is stored on : {x.device}")

Device tensor is stored on : cpu


In [8]:
print(x)
x = x + 1
x

tensor([[1.9292, 1.7509, 1.0860, 1.4008],
        [1.2181, 1.7912, 1.2149, 1.2868],
        [1.7526, 1.2620, 1.3840, 1.4162]])


tensor([[2.9292, 2.7509, 2.0860, 2.4008],
        [2.2181, 2.7912, 2.2149, 2.2868],
        [2.7526, 2.2620, 2.3840, 2.4162]])

In [10]:
import torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1,3,64,64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/kilingcheung/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth


In [11]:
prediction = model(data)

In [13]:
loss = (prediction - labels).sum()
loss.backward()

In [14]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [15]:
optim.step()

In [16]:
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

In [17]:
Q = 3*a**3 - b**2

In [19]:
Q, a, b

(tensor([-12.,  65.], grad_fn=<SubBackward0>),
 tensor([2., 3.], requires_grad=True),
 tensor([6., 4.], requires_grad=True))

In [20]:
external_grad = torch.tensor([1.,1.])
Q.backward(gradient=external_grad)

In [21]:
a.grad, b.grad

(tensor([36., 81.]), tensor([-12.,  -8.]))

In [22]:
print(9*a**2, -2*b)

tensor([36., 81.], grad_fn=<MulBackward0>) tensor([-12.,  -8.], grad_fn=<MulBackward0>)


In [34]:
import torch.nn as nn

In [33]:
target = torch.randn(10)
print(target)
target = target.view(1,-1)
target.size()

tensor([-0.4762, -0.2049, -0.3061,  0.4685, -0.4765,  1.2930, -0.1513,  0.2410,
        -0.3915, -0.8265])


torch.Size([1, 10])

In [31]:
help(target.view)

Help on built-in function view:

view(...) method of torch.Tensor instance
    view(*shape) -> Tensor
    
    Returns a new tensor with the same data as the :attr:`self` tensor but of a
    different :attr:`shape`.
    
    The returned tensor shares the same data and must have the same number
    of elements, but may have a different size. For a tensor to be viewed, the new
    view size must be compatible with its original size and stride, i.e., each new
    view dimension must either be a subspace of an original dimension, or only span
    across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
    contiguity-like condition that :math:`\forall i = d, \dots, d+k-1`,
    
    .. math::
    
      \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
    
    Otherwise, it will not be possible to view :attr:`self` tensor as :attr:`shape`
    without copying it (e.g., via :meth:`contiguous`). When it is unclear whether a
    :meth:`view` can be performe