In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
d = 5
m = 1 # number of movements: a
gamma = 0.5
def init1():
    # initalization to zeroes
    T = np.zeros((m, d, d))
    R = np.zeros((m, d, d))
    V = np.zeros(d)
    
    # assign value to T, R, V
    for n in np.arange(d-1):
        T[m-1,n,n+1] = 1
    T[m-1, d-1, d-1]= 1
    for n in np.arange(m):
        R[m-1, d-1, d-1] = 1
    return T,R,V

In [3]:
## init2
d = 5
m = 3 # number of movements: a
gamma = 0.5
def init2():
    # initalization to zeroes
    T = np.zeros((m, d, d))
    R = np.zeros((m, d, d))
    V = np.zeros(d)
    
    # assign value to T, R, V
    # for stay movement
    stay = 0
    left = 1
    right = 2
    # for stay movement
    for n in np.arange(d):
        T[stay,n,n] = 1/2
        if (n != 0) and (n != d-1):
            T[stay,n,n-1] = 1/4
            T[stay,n,n+1] = 1/4
    T[stay,0,1] = 1/2
    T[stay,d-1,d-2] = 1/2
    
    # for left movement
    for n in np.arange(1,d):
        T[left,n,n-1] = 1/3
        T[left,n,n] = 2/3
    T[left,0,0] = 1/2
    T[left,0,1] = 1/2
    
    # for right movement
    for n in np.arange(d-1):
        T[right,n,n+1] = 1/3
        T[right,n,n] = 2/3
    T[right,d-1,d-1] = 1/2
    T[right,d-1,d-2] = 1/2
    
    for n in np.arange(m):
        R[n, d-1, d-1] = 1
    # R[stay, d-1, d-1] = 1
    return T,R,V

In [4]:
T,R,V = init2()
T,R,V

(array([[[0.5       , 0.5       , 0.        , 0.        , 0.        ],
         [0.25      , 0.5       , 0.25      , 0.        , 0.        ],
         [0.        , 0.25      , 0.5       , 0.25      , 0.        ],
         [0.        , 0.        , 0.25      , 0.5       , 0.25      ],
         [0.        , 0.        , 0.        , 0.5       , 0.5       ]],
 
        [[0.5       , 0.5       , 0.        , 0.        , 0.        ],
         [0.33333333, 0.66666667, 0.        , 0.        , 0.        ],
         [0.        , 0.33333333, 0.66666667, 0.        , 0.        ],
         [0.        , 0.        , 0.33333333, 0.66666667, 0.        ],
         [0.        , 0.        , 0.        , 0.33333333, 0.66666667]],
 
        [[0.66666667, 0.33333333, 0.        , 0.        , 0.        ],
         [0.        , 0.66666667, 0.33333333, 0.        , 0.        ],
         [0.        , 0.        , 0.66666667, 0.33333333, 0.        ],
         [0.        , 0.        , 0.        , 0.66666667, 0.33333333],


In [5]:
num_step = 100
for iter in range(1, num_step+1):
    V_new = np.copy(V)
    for state in range(d):
        # if (iter > 1) and (state == d-1):
            # continue
        temp = np.zeros(m)
        for movement in range(m):
            for i in range(d):
                if (T[movement, state, i] > 0):
                    temp[movement] = temp[movement] + T[movement,state,i]* \
                                (R[movement,state,i] + gamma*V[i])
        V_new[state] = np.max(temp)
    V = V_new
    print(V)

[0.         0.         0.         0.         0.66666667]
[0.         0.         0.         0.11111111 0.88888889]
[0.         0.         0.01851852 0.18518519 0.98148148]
[0.         0.00308642 0.03703704 0.22530864 1.02469136]
[7.71604938e-04 7.20164609e-03 4.98971193e-02 2.45884774e-01
 1.04578189e+00]
[0.00199331 0.01071674 0.05761317 0.25625857 1.05624143]
[0.00317751 0.01317444 0.06191415 0.26145976 1.0614569 ]
[0.00408799 0.01471051 0.06421468 0.26406274 1.06406226]
[0.00469962 0.01560595 0.06541535 0.26536462 1.06536454]
[0.00507639 0.01610454 0.06603255 0.26601563 1.06601562]
[0.00529523 0.01637361 0.06634679 0.26634115 1.06634114]
[0.00541721 0.01651567 0.06650579 0.26650391 1.06650391]
[0.00548322 0.01658952 0.06658591 0.26658529 1.06658529]
[0.00551818 0.01662749 0.06662619 0.26662598 1.06662598]
[0.00553642 0.01664686 0.06664639 0.26664632 1.06664632]
[0.00554582 0.01665669 0.06665652 0.26665649 1.06665649]
[0.00555063 0.01666165 0.06666159 0.26666158 1.06666158]
[0.0055530

In [6]:
np.argmax(T[0,0])

0

In [7]:
0.0 > 0.0

False

In [8]:
[0.00555556, 0.01666667, 0.06666667, 0.26666667, 1.06666667]

[0.00555556, 0.01666667, 0.06666667, 0.26666667, 1.06666667]

In [9]:
V0 = np.zeros(4)
V1 = np.zeros(4)
up = 0
down = 1
T = np.ones((4,2))
T[0,down] = 0
T[3,up] = 0
R = np.array([[1,0],[1,1],[10,1],[0,10]])
gamma = 0.75

In [10]:
for iter in range(1,3):
    if (iter % 2 == 1):
        Vnew = V1
        Vold = V0
    else:
        Vnew = V0
        Vold = V1
    for i in np.arange(4):
        for j in [up, down]:
            t1 = T

In [12]:
vb = 1
vc = 10
gamma = 0.75
for iter in range(2,200):
    vb = 1 + gamma * vc
    vc = 10 + gamma * vc
    print('vb = ',vb, ' vc = ', vc)

vb =  8.5  vc =  17.5
vb =  14.125  vc =  23.125
vb =  18.34375  vc =  27.34375
vb =  21.5078125  vc =  30.5078125
vb =  23.880859375  vc =  32.880859375
vb =  25.66064453125  vc =  34.66064453125
vb =  26.9954833984375  vc =  35.9954833984375
vb =  27.996612548828125  vc =  36.996612548828125
vb =  28.747459411621094  vc =  37.747459411621094
vb =  29.31059455871582  vc =  38.31059455871582
vb =  29.732945919036865  vc =  38.732945919036865
vb =  30.04970943927765  vc =  39.04970943927765
vb =  30.287282079458237  vc =  39.28728207945824
vb =  30.465461559593678  vc =  39.46546155959368
vb =  30.599096169695258  vc =  39.59909616969526
vb =  30.699322127271444  vc =  39.699322127271444
vb =  30.774491595453583  vc =  39.77449159545358
vb =  30.830868696590187  vc =  39.83086869659019
vb =  30.87315152244264  vc =  39.87315152244264
vb =  30.90486364183198  vc =  39.90486364183198
vb =  30.928647731373985  vc =  39.928647731373985
vb =  30.94648579853049  vc =  39.94648579853049
vb =  

In [28]:
# for question 2
T = np.zeros((2,6,6))
M = 0
C = 1
T[M,0,0] = 1
T[C,0,0] = 1

T[M,1,0] =1
T[C,1,1] = 0.3
T[C,1,3] = 0.7

T[M,2,1] = 1
T[C,2,2] = 0.3
T[C,2,4] = 0.7

T[M,3,2] = 1
T[C,3,3] = 0.3
T[C,3,5] = 0.7

T[M,4,3] = 1
T[C,4,4] = 1

T[M,5,4] = 1
T[C,5,5] = 1


R = np.zeros((2,6,6))
for i in range(6):
    if (i == 0):
        continue
    for j in range(6):
        if (i == j):
            R[M,i,j] = (i+4)**-0.5
            R[C,i,j] = (i+4)**-0.5
        else:
            R[M,i,j] = (np.abs(i-j))**(1/3)
            R[C,i,j] = (np.abs(i-j))**(1/3)
gamma = 0.6
T,R

(array([[[1. , 0. , 0. , 0. , 0. , 0. ],
         [1. , 0. , 0. , 0. , 0. , 0. ],
         [0. , 1. , 0. , 0. , 0. , 0. ],
         [0. , 0. , 1. , 0. , 0. , 0. ],
         [0. , 0. , 0. , 1. , 0. , 0. ],
         [0. , 0. , 0. , 0. , 1. , 0. ]],
 
        [[1. , 0. , 0. , 0. , 0. , 0. ],
         [0. , 0.3, 0. , 0.7, 0. , 0. ],
         [0. , 0. , 0.3, 0. , 0.7, 0. ],
         [0. , 0. , 0. , 0.3, 0. , 0.7],
         [0. , 0. , 0. , 0. , 1. , 0. ],
         [0. , 0. , 0. , 0. , 0. , 1. ]]]),
 array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
          0.        ],
         [1.        , 0.4472136 , 1.        , 1.25992105, 1.44224957,
          1.58740105],
         [1.25992105, 1.        , 0.40824829, 1.        , 1.25992105,
          1.44224957],
         [1.44224957, 1.25992105, 1.        , 0.37796447, 1.        ,
          1.25992105],
         [1.58740105, 1.44224957, 1.25992105, 1.        , 0.35355339,
          1.        ],
         [1.70997595, 1.58740105, 1.4

In [33]:
Q = np.zeros((2,6,2))
trial = 1
for iter in range(1,trial+1):
    Q_old = Q[(i-1)%2]
    Q_new = Q[i%2]
    for s in range(6):
        for a in [M,C]:
            tmp = 0
            for s_prime in range(6):
                if (T[a,s,s_prime] != 0):
                    ans = "s = {}, a = {}, s_prime = {}".format(s,a,s_prime)
                    print(ans)
                    tmp1 = R[a,s,s_prime] + gamma * max(Q_old[s_prime,M],Q_old[s_prime,C])
                    tmp = tmp + tmp1 * T[a,s,s_prime]
                    ans = "tmp = {}".format(tmp)
                    print(ans)
            Q_new[s,a] = tmp
print(Q)

s = 0, a = 0, s_prime = 0
tmp = 0.0
s = 0, a = 1, s_prime = 0
tmp = 0.0
s = 1, a = 0, s_prime = 0
tmp = 1.0
s = 1, a = 1, s_prime = 1
tmp = 0.13416407864998736
s = 1, a = 1, s_prime = 3
tmp = 1.0161088135763985
s = 2, a = 0, s_prime = 1
tmp = 1.0
s = 2, a = 1, s_prime = 2
tmp = 0.1224744871391589
s = 2, a = 1, s_prime = 4
tmp = 1.00441922206557
s = 3, a = 0, s_prime = 2
tmp = 1.0
s = 3, a = 1, s_prime = 3
tmp = 0.11338934190276817
s = 3, a = 1, s_prime = 5
tmp = 0.9953340768291793
s = 4, a = 0, s_prime = 3
tmp = 1.0
s = 4, a = 1, s_prime = 4
tmp = 0.3535533905932738
s = 5, a = 0, s_prime = 4
tmp = 1.0
s = 5, a = 1, s_prime = 5
tmp = 0.3333333333333333
[[[0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.         0.        ]
  [1.         1.01610881]
  [1.         1.00441922]
  [1.         0.99533408]
  [1.         0.35355339]
  [1.         0.33333333]]]


In [34]:
0.3*0.4472+0.7*1.26

1.01616

In [35]:
from typing import NamedTuple, Tuple

In [36]:
class GuassianM(NamedTuple):
    mu: np.ndarray
    var: np.ndarray
    p: np.ndarray

In [37]:
a1 = np.array([0,1,2])
a2 = np.array([2,3,4])
p = np.array([4,5,6])
gm = GuassianM(a1,a2,p)
gm

GuassianM(mu=array([0, 1, 2]), var=array([2, 3, 4]), p=array([4, 5, 6]))