In [31]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.stats import norm

In [48]:
x = np.array([0.2, -0.9, -1, 1.2, 1.8])
mu = np.array([-3,2])
var = np.array([4,4])
pj = np.array([0.5,0.5])
nn = np.array([norm.pdf(x[0],loc=mu[0], scale=np.sqrt(var[0])), 
              norm.pdf(x[0],loc=mu[1], scale=np.sqrt(var[1]))])
for i in np.arange(1,len(x)):
    n1 = np.array([norm.pdf(x[i],loc=mu[0], scale=np.sqrt(var[0])), 
              norm.pdf(x[i],loc=mu[1], scale=np.sqrt(var[1]))])
    print('n1 = ', n1)
    nn = np.vstack((nn, n1))
print('nn = \n', nn)
px = np.matmul(nn, np.transpose(pj))
print('px = \n', px)
pj_x = nn * pj
print('pj_x = \n', pj_x)
pj_x = pj_x/px.reshape((5,1))
print('pj_x = \n', pj_x)

nj = np.sum(pj_x, axis=0)
print('nj = ', nj)

# M step
pj = nj/len(x)
print('new pj = ', pj)
u = pj_x * x.reshape((5,1))
u = np.sum(u, axis=0)
mu = u/nj
print('new mu = ', mu)
v = np.array([x - mu[0], x-mu[1]])
v = v**2
v = pj_x * np.transpose(v)
v = np.sum(v, axis=0)
var = v/nj

print('var = ', var)

n1 =  [0.11494107 0.06971528]
n1 =  [0.12098536 0.0647588 ]
n1 =  [0.0219918  0.18413507]
n1 =  [0.01119727 0.19847627]
nn = 
 [[0.05546042 0.13304262]
 [0.11494107 0.06971528]
 [0.12098536 0.0647588 ]
 [0.0219918  0.18413507]
 [0.01119727 0.19847627]]
px = 
 [0.09425152 0.09232818 0.09287208 0.10306343 0.10483677]
pj_x = 
 [[0.02773021 0.06652131]
 [0.05747054 0.03485764]
 [0.06049268 0.0323794 ]
 [0.0109959  0.09206754]
 [0.00559863 0.09923814]]
pj_x = 
 [[0.29421497 0.70578503]
 [0.62245933 0.37754067]
 [0.65135486 0.34864514]
 [0.10669059 0.89330941]
 [0.05340333 0.94659667]]
nj =  [1.72812309 3.27187691]
new pj =  [0.34562462 0.65437538]
new mu =  [-0.53732895  0.6811291 ]
var =  [0.57578591 1.07524796]


In [50]:
x = np.array([0.2, -0.9, -1, 1.2, 1.8])
mu = np.array([-3,2])
var = np.array([4,4])
pj = np.array([0.5,0.5])

In [59]:

nn = np.array([norm.pdf(x[0],loc=mu[0], scale=np.sqrt(var[0])), 
              norm.pdf(x[0],loc=mu[1], scale=np.sqrt(var[1]))])
for i in np.arange(1,len(x)):
    n1 = np.array([norm.pdf(x[i],loc=mu[0], scale=np.sqrt(var[0])), 
              norm.pdf(x[i],loc=mu[1], scale=np.sqrt(var[1]))])
    print('n1 = ', n1)
    nn = np.vstack((nn, n1))
print('nn = \n', nn)
px = np.matmul(nn, np.transpose(pj))
print('px = \n', px)
pj_x = nn * pj
print('pj_x = \n', pj_x)
pj_x = pj_x/px.reshape((5,1))
print('pj_x = \n', pj_x)

nj = np.sum(pj_x, axis=0)
print('nj = ', nj)

# M step
pj = nj/len(x)
print('new pj = ', pj)
u = pj_x * x.reshape((5,1))
u = np.sum(u, axis=0)
mu = u/nj
print('new mu = ', mu)
v = np.array([x - mu[0], x-mu[1]])
v = v**2
v = pj_x * np.transpose(v)
v = np.sum(v, axis=0)
var = v/nj

print('var = ', var)

n1 =  [4.83732853 0.0075129 ]
n1 =  [4.84150045e+00 4.75405862e-03]
n1 =  [0.         0.58885948]
n1 =  [0.         0.32504372]
nn = 
 [[1.06346385e-114 2.57468835e-001]
 [4.83732853e+000 7.51290157e-003]
 [4.84150045e+000 4.75405862e-003]
 [0.00000000e+000 5.88859477e-001]
 [0.00000000e+000 3.25043723e-001]]
px = 
 [0.15467851 1.93573982 1.93574798 0.35376671 0.1952752 ]
pj_x = 
 [[4.24570994e-115 1.54678506e-001]
 [1.93122633e+000 4.51349534e-003]
 [1.93289190e+000 2.85607647e-003]
 [0.00000000e+000 3.53766715e-001]
 [0.00000000e+000 1.95275197e-001]]
pj_x = 
 [[2.74486097e-114 1.00000000e+000]
 [9.97668336e-001 2.33166425e-003]
 [9.98524562e-001 1.47543818e-003]
 [0.00000000e+000 1.00000000e+000]
 [0.00000000e+000 1.00000000e+000]]
nj =  [1.9961929 3.0038071]
new pj =  [0.39923858 0.60076142]
new mu =  [-0.95002145  1.06412494]
var =  [0.0025    0.4400973]


In [ ]:
nn[0]

In [49]:
26*26

676