In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

In [2]:
x = np.array(np.arange(1,13))
x = x.reshape(4,3)
y = np.array([1,-1,1,-1])
x,y

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([ 1, -1,  1, -1]))

In [3]:
factor = 2
t1 = np.matmul(np.transpose(x), x) + factor * np.identity(x.shape[1])
np.linalg.inv(t1)

array([[ 0.24161074, -0.15436242, -0.05033557],
       [-0.15436242,  0.33473154, -0.1761745 ],
       [-0.05033557, -0.1761745 ,  0.19798658]])

In [4]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
def closed_form(X, Y, lambda_factor):
    X_transpose = np.transpose(X)
    t1 = np.matmul(X_transpose, X) + lambda_factor * np.identity(X.shape[1])
    t2 = np.matmul(np.linalg.inv(t1), X_transpose)
    theta = np.matmul(t2, Y)
    return theta

In [6]:
theta_1 = closed_form(x, y, 2)
theta_1

array([-0.22147651, -0.02516779,  0.17114094])

In [7]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [8]:
clf = SVC(kernel="linear", random_state=0, C=0.1)
clf.fit(x,y)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [9]:
y_pred = clf.predict(x)
accuracy_score(y, y_pred)

0.5

In [10]:
clf2 = LinearSVC(random_state=0, C=0.1)
clf2.fit(x,y)
y_pred2 = clf2.predict(x)
accuracy_score(y, y_pred2)

0.75

In [11]:
#help(LinearSVC)

In [12]:
clf3 = LinearSVC(random_state=0, multi_class='ovr')
clf3.fit(x,y)
y_pred3 = clf3.predict(x)
accuracy_score(y, y_pred3)

/Users/kilingcheung/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.5

In [13]:
theta = theta_1.reshape(3,1)

In [14]:
tau = 0.5
t1 = np.matmul(x, theta)
np.exp(t1)

array([[1.27329845],
       [1.01521526],
       [0.80944262],
       [0.64537776]])

In [57]:
def compute_prob(X, theta, temp_parameter):
    t1 = np.matmul(theta, np.transpose(X))/temp_parameter
    c = np.max(t1)
    t1 = t1 - c
    numerator = np.exp(t1)
    denominator = np.sum(numerator, axis=0)
    print(numerator, denominator)
    return numerator, denominator

In [58]:
#compute_prob(x, theta, tau)

In [59]:
#help(np.max)

In [60]:
def check_compute_probabilities():
    ex_name = "Compute probabilities"
    n, d, k = 3, 5, 7
    X = np.arange(0, n * d).reshape(n, d)
    zeros = np.zeros((k, d))
    temp = 0.2
    exp_res = np.ones((k, n)) / k

    theta = np.arange(0, k * d).reshape(k, d)
    ans = compute_prob(X, theta, temp)
    exp_res = np.zeros((k, n))
    exp_res[-1] = 1
    
    return exp_res, ans

In [81]:
from scipy.special import softmax

def prob3():
    ex_name = "Compute probabilities"
    n, d, k = 3, 5, 7
    X = np.arange(0, n * d).reshape(n, d)
    zeros = np.zeros((k, d))
    temp = 0.2
    exp_res = np.ones((k, n)) / k

    exp_res[-1] = 1
    ans = softmax(X)
    return ans

prob3()

array([[5.25626559e-07, 1.42880112e-06, 3.88388413e-06, 1.05574917e-05,
        2.86982378e-05],
       [7.80098982e-05, 2.12052889e-04, 5.76419514e-04, 1.56687069e-03,
        4.25919613e-03],
       [1.15776954e-02, 3.14714391e-02, 8.55482410e-02, 2.32544229e-01,
        6.32120752e-01]])

In [80]:
def prob2():
    ex_name = "Compute probabilities"
    n, d, k = 3, 5, 7
    X = np.arange(0, n * d).reshape(n, d)
    zeros = np.zeros((k, d))
    temp = 0.2
    exp_res = np.ones((k, n)) / k

    # eta = np.zeros((k, d))
    theta = np.arange(0, k * d).reshape(k, d)
    exp_res = np.zeros((k, n))
    exp_res[-1] = 1
    
    t1 = np.matmul(theta, np.transpose(X))/temp
    c = np.max(t1)
    t2= t1 - c
    numerator = np.exp(t2)
    # nominator = np.sum(numerator, axis=0)
    
    
    # ans = compute_prob(X, theta, temp)
    
    #rint(exp_res, '\n', numerator, '\n', denominator, '\n', numerator/denominator)
    print('t1: ', t1, '\n', c, '\n', t2, '\n', numerator)
    
prob2()

t1:  [[ 150.  400.  650.]
 [ 400. 1275. 2150.]
 [ 650. 2150. 3650.]
 [ 900. 3025. 5150.]
 [1150. 3900. 6650.]
 [1400. 4775. 8150.]
 [1650. 5650. 9650.]] 
 9650.0 
 [[-9500. -9250. -9000.]
 [-9250. -8375. -7500.]
 [-9000. -7500. -6000.]
 [-8750. -6625. -4500.]
 [-8500. -5750. -3000.]
 [-8250. -4875. -1500.]
 [-8000. -4000.     0.]] 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


In [63]:
check_compute_probabilities()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]] [0. 0. 1.]


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.]]),
 (array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 1.]]),
  array([0., 0., 1.])))

In [33]:
1/7

0.14285714285714285

In [34]:
x1 =np.arange(1,13).reshape(4,3)
x1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
t1 = np.linalg.norm(x, axis=1)
print(t1, max(t1))

[ 3.74165739  8.77496439 13.92838828 19.10497317] 19.1049731745428


In [37]:
14**0.5

3.7416573867739413

In [41]:
#help(np.sum)

In [88]:
print(x)
np.max(x, axis=0), np.max(x, axis=1)
t4 = np.max(x, axis=1)
t5 = t4[:, np.newaxis]
print(t4, t5)
x-t5

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 3  6  9 12] [[ 3]
 [ 6]
 [ 9]
 [12]]


array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [90]:
print(x)
np.max(x, axis=0)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([10, 11, 12])

In [91]:
np.sum(x, axis=0)

array([22, 26, 30])