In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

In [37]:
def f(Z):
    t2 = np.apply_along_axis(lambda m: m if m > 0 else 0, 1, Z)
    return t2

In [38]:
def getZ(X, W):
    return np.matmul(W, X)

In [39]:
def u(fZ, V):
    return np.matmul(V, fZ)

In [40]:
t1 = np.array([1,0,-1,5]).reshape(4,1)
np.apply_along_axis(lambda x: x if x > 0 else 0, 1, t1)

array([[1],
       [0],
       [0],
       [5]])

In [41]:
def getOutput(U):
    fu = f(U)
    t1 = np.exp(fu)
    t1 = t1/(np.sum(t1))

In [42]:
w = np.array([[1, 0, -1], [0, 1, -1], [-1,0,-1],[0,-1,-1]])
v = np.array([[1,1,1,1,0],[-1,-1,-1,-1,2]])
w,v

(array([[ 1,  0, -1],
        [ 0,  1, -1],
        [-1,  0, -1],
        [ 0, -1, -1]]),
 array([[ 1,  1,  1,  1,  0],
        [-1, -1, -1, -1,  2]]))

In [43]:
x = np.array([3,14,1]).reshape(3,1)
x

array([[ 3],
       [14],
       [ 1]])

In [44]:
z = getZ(x,w)
fz = f(z)
z,fz

(array([[  2],
        [ 13],
        [ -4],
        [-15]]),
 array([[ 2],
        [13],
        [ 0],
        [ 0]]))

In [59]:
k1 = np.array([[0,1,1,1]])
k1 = np.append(k1,[1]).reshape(5,1)
k1,k1.shape, fz.shape

(array([[0],
        [1],
        [1],
        [1],
        [1]]),
 (5, 1),
 (4, 1))

In [60]:
u12 = u(k1, v)
u12

array([[ 3],
       [-1]])

In [61]:
t2 = f(u12)
t2

array([[3],
       [0]])

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-1*x))

In [69]:
def ft_1(Wh, Wx, H, X, B):
    t1 = np.matmul(Wh, H) + np.matmul(Wx, X) + B
    return sigmoid(t1)

def ft_2(Wh, Wx, H, X, B):
    t1 = Wh * H + Wx * X + B
    return sigmoid(t1)

In [70]:
ft_2(1, 2, 3, 4, 0)

0.999983298578152

In [89]:
def getc(F, C, I, Wh, Wx, H, X, B):
    t1 = Wh * H + Wx * X + B
    ct = F * C + I * np.tanh(t1)
    return ct

In [82]:
def geth(OT, CT):
    return OT* np.tanh(CT)

In [81]:
w_fh = 0 
w_fx = 0 
bf = -100
w_ch = -100
w_ih = 0 
w_ix = 100 
bi = 100 
w_cx = 50
w_oh=0 
w_ox = 100 
bo = 0 
bc = 0

In [90]:
i = 0
h = 0
c = 0
x_all = np.array([0,0,1,1,1,0])

def cal(c, h, x):
    f_t = ft_2(w_fh, w_fx, h, x, bf)
    i_t = ft_2(w_ih, w_ix, h, x, bi)
    o_t = ft_2(w_oh, w_ox, h, x, bo)
    ct = getc(f_t, c, i_t, w_ch, w_cx, h, x, bc)
    ht = geth(o_t, ct)
    return ct, ht

In [91]:
i=0
c, h = cal(c,h,x_all[i])
c,h

(0.0, 0.0)

In [93]:
x_all = np.array([1,1,0,1,1])
h = 0
c = 0
for i in np.arange(5):
    c, h = cal(c, h, x_all[i])
    print('i = ', i, 'c = ', c, 'h = ', h)

i =  0 c =  1.0 h =  0.7615941559557649
i =  1 c =  -1.0 h =  -0.7615941559557649
i =  2 c =  1.0 h =  0.3807970779778824
i =  3 c =  0.9999999999114485 h =  0.7615941559185755
i =  4 c =  -1.0 h =  -0.7615941559557649


In [18]:
def relu(Z):
    return max(0, Z)

def simple_network():
    t = 1
    x = 3
    w1 = 0.01
    w2 = -5
    b = -1
    
    z1 = w1 * x
    a1 = relu(z1)
    z2 = w2 * a1 + b
    y = sigmoid(z2)
    C = 0.5 * (y-t)**2
    
    ans = "z1 = {}, a1 = {}, z2 = {}, y = {}, C = {}".format(z1,a1,z2,y,C)
    print(ans)
    
    dc_dw1 = (y-t) * dy_dz2(z2) * w2 * da1_dz1(z1) * x
    print('dc_dw1 =', dc_dw1)
    
    dc_dw2 = (y-t) * dy_dz2(z2) *a1
    print('dc_dw2 = ', dc_dw2)
    
    dc_db = (y-t) * dy_dz2(z2) *1
    print('dc_db = ', dc_db)

In [19]:
simple_network()

z1 = 0.03, a1 = 0.03, z2 = -1.15, y = 0.24048908305088898, C = 0.28842841648243966
dc_dw1 = 2.080916562170455
dc_dw2 =  -0.004161833124340909
dc_db =  -0.13872777081136364


In [13]:
def dc_dy(Y,T):
    return Y-T

def dy_dz2(Z):
    val = np.exp(Z)
    return val/(1+val)**2

def dz2_w2(A):
    return A

def dz2_a1(W):
    return W

def dz2_b(B):
    return 1

def da1_dz1(Z):
    if Z > 0:
        return 1
    else:
        return 0
    
def dz1_w1(X):
    return 

In [7]:
f1 = np.array([1,2,3])
g1 = np.array([2,1])
g2 = np.convolve(f1,g1,mode='valid')
g3 = np.convolve(f1,g1,mode='full')
f1,g1,g2,g3

(array([1, 2, 3]), array([2, 1]), array([5, 8]), array([2, 5, 8, 3]))

In [10]:
f1 = np.array([1,3,-1,1,-3])
g1 = np.array([-1,0,1])
g2 = np.convolve(f1,g1,mode='full')
g2

array([-1, -3,  2,  2,  2,  1, -3])

In [11]:
help(np.correlate)

Help on function correlate in module numpy:

correlate(a, v, mode='valid')
    Cross-correlation of two 1-dimensional sequences.
    
    This function computes the correlation as generally defined in signal
    processing texts::
    
        c_{av}[k] = sum_n a[n+k] * conj(v[n])
    
    with a and v sequences being zero-padded where necessary and conj being
    the conjugate.
    
    Parameters
    ----------
    a, v : array_like
        Input sequences.
    mode : {'valid', 'same', 'full'}, optional
        Refer to the `convolve` docstring.  Note that the default
        is 'valid', unlike `convolve`, which uses 'full'.
    old_behavior : bool
        `old_behavior` was removed in NumPy 1.10. If you need the old
        behavior, use `multiarray.correlate`.
    
    Returns
    -------
    out : ndarray
        Discrete cross-correlation of `a` and `v`.
    
    See Also
    --------
    convolve : Discrete, linear convolution of two one-dimensional sequences.
    multiarray.cor

In [14]:
f1 = np.array([1,2,3])
g1 = np.array([1,2])
h = np.correlate(f1,g1,"full")
f1,g1,h

(array([1, 2, 3]), array([1, 2]), array([2, 5, 8, 3]))

In [17]:
from scipy import signal

In [19]:
f1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
g1 = np.array([[1,0],[0,1]])
h = signal.correlate2d(f1,g1,"full")
h

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])