In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import torch

In [2]:
some_ones = torch.ones(2,2)
some_zeroes = torch.zeros(2,2)
some_normals = torch.randn(2,2)
print(some_ones, some_zeroes, some_normals)

tensor([[1., 1.],
        [1., 1.]]) tensor([[0., 0.],
        [0., 0.]]) tensor([[-0.2894,  1.5891],
        [ 0.8526, -1.2486]])


In [3]:
torch_tensor = torch.randn(5,5)
numpy_ndarray = torch_tensor.numpy()
back_to_torch = torch.from_numpy(numpy_ndarray)

In [4]:
type(torch_tensor.numpy())

numpy.ndarray

In [5]:
a = torch.randn(5,5)
b = torch.randn(5,5)
a,b

(tensor([[ 0.9778,  1.3684,  0.1286,  0.3441, -1.3430],
         [ 0.5586,  0.6562, -0.8346, -0.1246,  0.1214],
         [ 1.3994, -1.1964,  1.4761, -2.2471, -0.3135],
         [ 1.7451, -2.1885,  2.1255, -2.4344, -0.4238],
         [-0.1482,  0.0703, -1.2478,  0.5469,  0.0381]]),
 tensor([[-0.4232, -1.1714, -1.9961, -1.8511,  1.1269],
         [ 1.1135, -0.4517, -0.7750, -0.3368, -0.1573],
         [-0.4077,  0.9639,  0.0653,  1.8939,  1.9101],
         [ 0.6808,  0.8487, -0.4325, -0.3282, -0.1848],
         [ 1.0850, -0.3815, -0.6001,  0.8152,  0.0907]]))

In [6]:
another_tensor = a[2,2]
print(type(another_tensor), another_tensor)
print(another_tensor.item(), type(another_tensor.item()))

<class 'torch.Tensor'> tensor(1.4761)
1.4761170148849487 <class 'float'>


In [7]:
another_tensor.item()

1.4761170148849487

In [8]:
a.size()
vec = a[:, 0]
type(vec), vec.size()

(torch.Tensor, torch.Size([5]))

In [9]:
a = torch.randn(5,5)
c = a.unsqueeze(-1)
print(c.size(), c)
print(a)

torch.Size([5, 5, 1]) tensor([[[ 0.2046],
         [-1.5883],
         [-0.5253],
         [ 0.1205],
         [-0.7745]],

        [[ 0.1242],
         [-0.5797],
         [ 0.3491],
         [-0.7921],
         [ 0.3318]],

        [[-0.0632],
         [ 0.1020],
         [-0.8465],
         [-0.5435],
         [ 0.6456]],

        [[-0.4088],
         [ 1.8035],
         [-0.2283],
         [ 1.7266],
         [-1.8089]],

        [[ 0.3705],
         [-1.6050],
         [-0.1363],
         [-1.0440],
         [ 0.6272]]])
tensor([[ 0.2046, -1.5883, -0.5253,  0.1205, -0.7745],
        [ 0.1242, -0.5797,  0.3491, -0.7921,  0.3318],
        [-0.0632,  0.1020, -0.8465, -0.5435,  0.6456],
        [-0.4088,  1.8035, -0.2283,  1.7266, -1.8089],
        [ 0.3705, -1.6050, -0.1363, -1.0440,  0.6272]])


In [10]:
print(c[0,:,:])

tensor([[ 0.2046],
        [-1.5883],
        [-0.5253],
        [ 0.1205],
        [-0.7745]])


In [11]:
a = torch.randn(2)
print(a)
a = a.unsqueeze(-1)
print(a)

tensor([-2.2077,  0.9409])
tensor([[-2.2077],
        [ 0.9409]])


In [12]:
torch.cuda.is_available()

False

In [13]:
a = torch.randn(5,3,3)
b = torch.randn(5,3,3)
print(a, a[0,:,:])

tensor([[[ 0.9201,  1.1039,  1.1766],
         [-0.8145, -0.7267,  1.6856],
         [ 0.7477,  1.1827, -0.1955]],

        [[-1.9920,  0.0821, -1.5514],
         [ 1.0847, -0.6799, -1.3115],
         [-0.5174,  0.8067, -2.5106]],

        [[ 0.6026,  0.6728, -0.9120],
         [ 0.9425, -0.1461, -0.7508],
         [-1.8380, -0.3307,  1.6907]],

        [[ 1.1013,  1.4225, -1.3139],
         [-0.3674,  0.1213,  1.0319],
         [-2.1428, -0.6336, -0.3333]],

        [[ 0.9889, -0.6999, -0.0849],
         [-1.1034, -0.6842,  0.9954],
         [ 1.6170, -1.0193, -0.6379]]]) tensor([[ 0.9201,  1.1039,  1.1766],
        [-0.8145, -0.7267,  1.6856],
        [ 0.7477,  1.1827, -0.1955]])


In [14]:
x = torch.randn(1, requires_grad=True)
print(x)

tensor([-0.5082], requires_grad=True)


In [15]:
print(x.grad)

None


In [16]:
y = x.exp()
y

tensor([0.6016], grad_fn=<ExpBackward>)

In [17]:
y.backward()

In [18]:
print(x.grad,y)

tensor([0.6016]) tensor([0.6016], grad_fn=<ExpBackward>)


In [19]:
x1 = torch.randn(2, requires_grad=True)
print(x1)
y = x1.exp()
print(y)
y[0].backward()
print(x.grad,y)

tensor([-0.2144, -0.7877], requires_grad=True)
tensor([0.8070, 0.4549], grad_fn=<ExpBackward>)
tensor([0.6016]) tensor([0.8070, 0.4549], grad_fn=<ExpBackward>)


In [20]:
x_a = torch.randn(1, requires_grad=True)
x_b = torch.randn(1, requires_grad=True)
print(x_a, x_b)
x = x_a * x_b
x1 = x**2
x2 = 1/x1
x3 = x2.exp()
x4 = 1 + x3
x5 = x4.log()
x6 = x5 ** (1/3)
x2.backward()
print(x_a.grad, x_b.grad)
print(-2/x**3)

tensor([0.3811], requires_grad=True) tensor([0.3173], requires_grad=True)
tensor([-358.9839]) tensor([-431.0889])
tensor([-1131.3033], grad_fn=<MulBackward0>)


In [21]:
x_a = torch.randn(1, requires_grad=True)
x_b = torch.randn(1, requires_grad=True)
print(x_a, x_b)
x = x_a * x_b
print(x)
x.backward()
print(x_a.grad, x_b.grad)

tensor([0.0880], requires_grad=True) tensor([0.9394], requires_grad=True)
tensor([0.0827], grad_fn=<MulBackward0>)
tensor([0.9394]) tensor([0.0880])


In [22]:
from sklearn.datasets import make_classification

In [23]:
#help(make_classification)

In [24]:
import torch.nn as nn

In [26]:
#help(nn.Sequential)

In [27]:
model = nn.Sequential(
            nn.Linear(784,10),
            nn.LeakyReLU(),
            nn.Linear(10,10))

In [28]:
import torchvision