In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn

In [37]:
def f(Z):
    t2 = np.apply_along_axis(lambda m: m if m > 0 else 0, 1, Z)
    return t2

In [38]:
def getZ(X, W):
    return np.matmul(W, X)

In [39]:
def u(fZ, V):
    return np.matmul(V, fZ)

In [40]:
t1 = np.array([1,0,-1,5]).reshape(4,1)
np.apply_along_axis(lambda x: x if x > 0 else 0, 1, t1)

array([[1],
       [0],
       [0],
       [5]])

In [41]:
def getOutput(U):
    fu = f(U)
    t1 = np.exp(fu)
    t1 = t1/(np.sum(t1))

In [42]:
w = np.array([[1, 0, -1], [0, 1, -1], [-1,0,-1],[0,-1,-1]])
v = np.array([[1,1,1,1,0],[-1,-1,-1,-1,2]])
w,v

(array([[ 1,  0, -1],
        [ 0,  1, -1],
        [-1,  0, -1],
        [ 0, -1, -1]]),
 array([[ 1,  1,  1,  1,  0],
        [-1, -1, -1, -1,  2]]))

In [43]:
x = np.array([3,14,1]).reshape(3,1)
x

array([[ 3],
       [14],
       [ 1]])

In [44]:
z = getZ(x,w)
fz = f(z)
z,fz

(array([[  2],
        [ 13],
        [ -4],
        [-15]]),
 array([[ 2],
        [13],
        [ 0],
        [ 0]]))

In [59]:
k1 = np.array([[0,1,1,1]])
k1 = np.append(k1,[1]).reshape(5,1)
k1,k1.shape, fz.shape

(array([[0],
        [1],
        [1],
        [1],
        [1]]),
 (5, 1),
 (4, 1))

In [60]:
u12 = u(k1, v)
u12

array([[ 3],
       [-1]])

In [61]:
t2 = f(u12)
t2

array([[3],
       [0]])

In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-1*x))

In [69]:
def ft_1(Wh, Wx, H, X, B):
    t1 = np.matmul(Wh, H) + np.matmul(Wx, X) + B
    return sigmoid(t1)

def ft_2(Wh, Wx, H, X, B):
    t1 = Wh * H + Wx * X + B
    return sigmoid(t1)

In [70]:
ft_2(1, 2, 3, 4, 0)

0.999983298578152

In [89]:
def getc(F, C, I, Wh, Wx, H, X, B):
    t1 = Wh * H + Wx * X + B
    ct = F * C + I * np.tanh(t1)
    return ct

In [82]:
def geth(OT, CT):
    return OT* np.tanh(CT)

In [81]:
w_fh = 0 
w_fx = 0 
bf = -100
w_ch = -100
w_ih = 0 
w_ix = 100 
bi = 100 
w_cx = 50
w_oh=0 
w_ox = 100 
bo = 0 
bc = 0

In [90]:
i = 0
h = 0
c = 0
x_all = np.array([0,0,1,1,1,0])

def cal(c, h, x):
    f_t = ft_2(w_fh, w_fx, h, x, bf)
    i_t = ft_2(w_ih, w_ix, h, x, bi)
    o_t = ft_2(w_oh, w_ox, h, x, bo)
    ct = getc(f_t, c, i_t, w_ch, w_cx, h, x, bc)
    ht = geth(o_t, ct)
    return ct, ht

In [91]:
i=0
c, h = cal(c,h,x_all[i])
c,h

(0.0, 0.0)

In [93]:
x_all = np.array([1,1,0,1,1])
h = 0
c = 0
for i in np.arange(5):
    c, h = cal(c, h, x_all[i])
    print('i = ', i, 'c = ', c, 'h = ', h)

i =  0 c =  1.0 h =  0.7615941559557649
i =  1 c =  -1.0 h =  -0.7615941559557649
i =  2 c =  1.0 h =  0.3807970779778824
i =  3 c =  0.9999999999114485 h =  0.7615941559185755
i =  4 c =  -1.0 h =  -0.7615941559557649


In [18]:
def relu(Z):
    return max(0, Z)

def simple_network():
    t = 1
    x = 3
    w1 = 0.01
    w2 = -5
    b = -1
    
    z1 = w1 * x
    a1 = relu(z1)
    z2 = w2 * a1 + b
    y = sigmoid(z2)
    C = 0.5 * (y-t)**2
    
    ans = "z1 = {}, a1 = {}, z2 = {}, y = {}, C = {}".format(z1,a1,z2,y,C)
    print(ans)
    
    dc_dw1 = (y-t) * dy_dz2(z2) * w2 * da1_dz1(z1) * x
    print('dc_dw1 =', dc_dw1)
    
    dc_dw2 = (y-t) * dy_dz2(z2) *a1
    print('dc_dw2 = ', dc_dw2)
    
    dc_db = (y-t) * dy_dz2(z2) *1
    print('dc_db = ', dc_db)

In [19]:
simple_network()

z1 = 0.03, a1 = 0.03, z2 = -1.15, y = 0.24048908305088898, C = 0.28842841648243966
dc_dw1 = 2.080916562170455
dc_dw2 =  -0.004161833124340909
dc_db =  -0.13872777081136364


In [13]:
def dc_dy(Y,T):
    return Y-T

def dy_dz2(Z):
    val = np.exp(Z)
    return val/(1+val)**2

def dz2_w2(A):
    return A

def dz2_a1(W):
    return W

def dz2_b(B):
    return 1

def da1_dz1(Z):
    if Z > 0:
        return 1
    else:
        return 0
    
def dz1_w1(X):
    return 

In [7]:
f1 = np.array([1,2,3])
g1 = np.array([2,1])
g2 = np.convolve(f1,g1,mode='valid')
g3 = np.convolve(f1,g1,mode='full')
f1,g1,g2,g3

(array([1, 2, 3]), array([2, 1]), array([5, 8]), array([2, 5, 8, 3]))

In [10]:
f1 = np.array([1,3,-1,1,-3])
g1 = np.array([-1,0,1])
g2 = np.convolve(f1,g1,mode='full')
g2

array([-1, -3,  2,  2,  2,  1, -3])

In [11]:
help(np.correlate)

Help on function correlate in module numpy:

correlate(a, v, mode='valid')
    Cross-correlation of two 1-dimensional sequences.
    
    This function computes the correlation as generally defined in signal
    processing texts::
    
        c_{av}[k] = sum_n a[n+k] * conj(v[n])
    
    with a and v sequences being zero-padded where necessary and conj being
    the conjugate.
    
    Parameters
    ----------
    a, v : array_like
        Input sequences.
    mode : {'valid', 'same', 'full'}, optional
        Refer to the `convolve` docstring.  Note that the default
        is 'valid', unlike `convolve`, which uses 'full'.
    old_behavior : bool
        `old_behavior` was removed in NumPy 1.10. If you need the old
        behavior, use `multiarray.correlate`.
    
    Returns
    -------
    out : ndarray
        Discrete cross-correlation of `a` and `v`.
    
    See Also
    --------
    convolve : Discrete, linear convolution of two one-dimensional sequences.
    multiarray.cor

In [14]:
f1 = np.array([1,2,3])
g1 = np.array([1,2])
h = np.correlate(f1,g1,"full")
f1,g1,h

(array([1, 2, 3]), array([1, 2]), array([2, 5, 8, 3]))

In [17]:
from scipy import signal

In [19]:
f1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
g1 = np.array([[1,0],[0,1]])
h = signal.correlate2d(f1,g1,"full")
h

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [2]:
import torch

In [4]:
x_a = torch.randn(1, requires_grad=True)
x_b = torch.randn(1, requires_grad=True)
print(x_a, x_b)
x = x_a * x_b

tensor([1.5030], requires_grad=True) tensor([0.5391], requires_grad=True)


In [5]:
W1 = torch.randn(10, 2, requires_grad=True)
W1

tensor([[-0.5427,  0.4848],
        [ 0.4238, -0.4398],
        [ 1.2818,  0.2862],
        [-2.4152, -0.2637],
        [-0.0614, -0.1718],
        [ 0.1591,  0.4193],
        [ 2.0659, -1.9378],
        [-1.6786,  0.3529],
        [-0.6918,  0.1785],
        [ 1.0274, -0.9793]], requires_grad=True)

In [3]:
import torch.nn as nn

In [7]:
linear = nn.Linear(10,10)
print(linear)

Linear(in_features=10, out_features=10, bias=True)


In [8]:
conv = nn.Conv2d(1,20,5,1)
print(conv)

Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))


In [83]:
input_to_hidden_weights = np.matrix('1. 1.; 1. 1.; 1. 1.')
hidden_to_output_weights = np.matrix('1. 1. 1.')
biases = np.matrix('0.; 0.; 0.')
learning_rate = .001
epochs_to_train = 10
training_points = [((2,1), 10), ((3,3), 21), ((4,5), 32), ((6, 6), 42)]
print(input_to_hidden_weights)
print(input_to_hidden_weights.shape, hidden_to_output_weights.shape, hidden_to_output_weights.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2) (1, 3) (1, 3)


In [84]:
def rectified_linear_unit(x):
    """ Returns the ReLU of x, or the maximum between 0 and x."""
    # TODO
    return max(0, x)

def rectified_linear_unit_derivative(x):
    """ Returns the derivative of ReLU."""
    # TODO
    if (x <= 0):
        return 0
    else:
        return 1

def output_layer_activation(x):
    """ Linear function, returns input as is. """
    return x

def output_layer_activation_derivative(x):
    """ Returns the derivative of a linear function: 1. """
    return 1

In [85]:
x1 =2
x2 = 1
y = 10
#temp1 = np.matrix([[x1],[x2]])
temp1 = np.array([x1,x2]).reshape(2,1)
hidden_layer_weighted_input = np.matmul(input_to_hidden_weights,(temp1)) + \
                                        biases # TODO (3 by 1 matrix)
result_str = "temp1 = {} \ninput_to_hidden_weights = {} \nhidden_layer_weighted_input = {}".format(\
                                                        temp1, input_to_hidden_weights, hidden_layer_weighted_input)
print(result_str)

temp1 = [[2]
 [1]] 
input_to_hidden_weights = [[1. 1.]
 [1. 1.]
 [1. 1.]] 
hidden_layer_weighted_input = [[3.]
 [3.]
 [3.]]


In [86]:
x1 =2
x2 = 1
y = 10
#temp1 = np.matrix([[x1],[x2]])
temp1 = np.array([x1,x2]).reshape(2,1)

print('temp1 = ', temp1)
hidden_layer_weighted_input = np.matmul(input_to_hidden_weights, temp1) + \
                                        biases # TODO (3 by 1 matrix)
v_rectified_linear_unit = np.vectorize(rectified_linear_unit)
hidden_layer_activation = v_rectified_linear_unit(hidden_layer_weighted_input)# TODO (3 by 1 matrix)

output =  np.matmul(hidden_to_output_weights, hidden_layer_activation)# TODO
v_output_layer_activation = np.vectorize(output_layer_activation)
activated_output = v_output_layer_activation(output)# TODO
result_str = "Z = {}, \nf(Z) = {}, \nu1 = {}, \nf(u1) = {}".format(hidden_layer_weighted_input, \
                                                            hidden_layer_activation, output, activated_output)
print(result_str)
#txt3 = "My name is {}, I'm {}".format("John",36)
output_layer_error = (activated_output - y) * output_layer_activation_derivative(output) # TODO
v_rectified_linear_unit_derivative = np.vectorize(rectified_linear_unit_derivative)
hidden_layer_error = output_layer_error * hidden_to_output_weights # TODO (3 by 1 matrix)

temp1 =  [[2]
 [1]]
Z = [[3.]
 [3.]
 [3.]], 
f(Z) = [[3.]
 [3.]
 [3.]], 
u1 = [[9.]], 
f(u1) = [[9.]]


In [87]:
x1 =2
x2 = 1
y = 10
temp1 = np.matrix([[x1],[x2]])
temp1.shape

(2, 1)

In [88]:
x1 =2
x2 = 1
y = 10
#temp1 = np.matrix([[x1],[x2]])
temp1 = np.array([x1,x2]).reshape(2,1)

print('temp1 = ', temp1)
hidden_layer_weighted_input = np.matmul(input_to_hidden_weights, temp1) + \
                                        biases # TODO (3 by 1 matrix)
v_rectified_linear_unit = np.vectorize(rectified_linear_unit)
hidden_layer_activation = v_rectified_linear_unit(hidden_layer_weighted_input)# TODO (3 by 1 matrix)

output =  np.matmul(hidden_to_output_weights, hidden_layer_activation)# TODO
v_output_layer_activation = np.vectorize(output_layer_activation)
activated_output = v_output_layer_activation(output)# TODO
result_str = "Z = {}, \nf(Z) = {}, \nu1 = {}, \nf(u1) = {}".format(hidden_layer_weighted_input, \
                                                            hidden_layer_activation, output, activated_output)
print(result_str)
#txt3 = "My name is {}, I'm {}".format("John",36)
output_layer_error = (activated_output - y) * output_layer_activation_derivative(output) # TODO
v_rectified_linear_unit_derivative = np.vectorize(rectified_linear_unit_derivative)
hidden_layer_error = output_layer_error * hidden_to_output_weights # TODO (3 by 1 matrix)
print(hidden_layer_activation.shape, hidden_layer_error.shape)
hidden_layer_error = np.multiply(v_rectified_linear_unit_derivative(hidden_layer_activation), \
                                 np.transpose(hidden_layer_error))
result_str = "output_layer_error = {}, \nhidden_layer_error = {}".format(output_layer_error, hidden_layer_error)
print(result_str)

bias_gradients = hidden_layer_error # TODO
hidden_to_output_weight_gradients = hidden_layer_activation * output_layer_error# TODO
input_to_hidden_weight_gradients = hidden_layer_error *np.transpose(input_values)# TODO
result_str = "bias_gradients = {} \nhidden_to_output_weight_gradients = {} \
                            \ninput_to_hidden_weight_gradients = {}".format(bias_gradients, \
                                                                hidden_to_output_weight_gradients, \
                                                                input_to_hidden_weight_gradients)
print(result_str)

# Use gradients to adjust weights and biases using gradient descent
biases = biases - bias_gradients # TODO
input_to_hidden_weights = input_to_hidden_weights - input_to_hidden_weight_gradients# TODO
hidden_to_output_weights = hidden_to_output_weights - hidden_to_output_weight_gradients# TODO
result_str = "new values: \nbiases = {}, input_to_hidden_weights = {}, hidden_to_output_weights = {}".\
            format(biases, input_to_hidden_weights, hidden_to_output_weights)
print(result_str)

temp1 =  [[2]
 [1]]
Z = [[3.]
 [3.]
 [3.]], 
f(Z) = [[3.]
 [3.]
 [3.]], 
u1 = [[9.]], 
f(u1) = [[9.]]
(3, 1) (1, 3)
output_layer_error = [[-1.]], 
hidden_layer_error = [[-1.]
 [-1.]
 [-1.]]
bias_gradients = [[-1.]
 [-1.]
 [-1.]] 
hidden_to_output_weight_gradients = [[-3.]
 [-3.]
 [-3.]]                             
input_to_hidden_weight_gradients = [[-2. -1.]
 [-2. -1.]
 [-2. -1.]]
new values: 
biases = [[1.]
 [1.]
 [1.]], input_to_hidden_weights = [[3. 2.]
 [3. 2.]
 [3. 2.]], hidden_to_output_weights = [[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [15]:
x1 =2
x2 = 1
y = 10
temp1 = np.matrix([[x1],[x2]])
hidden_layer_weighted_input = np.matmul(input_to_hidden_weights, input_values) + \
                                        biases # TODO (3 by 1 matrix)
v_rectified_linear_unit = np.vectorize(rectified_linear_unit)
hidden_layer_activation = v_rectified_linear_unit(hidden_layer_weighted_input)# TODO (3 by 1 matrix)

output =  np.matmul(hidden_to_output_weights, hidden_layer_activation)# TODO
v_output_layer_activation = np.vectorize(output_layer_activation)
activated_output = v_output_layer_activation(output)# TODO

### Backpropagation ###

# Compute gradients
output_layer_error = (activated_output - y) * output_layer_activation_derivative(output) # TODO
v_rectified_linear_unit_derivative = np.vectorize(rectified_linear_unit_derivative)
hidden_layer_error = output_layer_error * hidden_to_output_weights # TODO (3 by 1 matrix)

bias_gradients = hidden_layer_error # TODO
hidden_to_output_weight_gradients = hidden_layer_activation * output_layer_error# TODO
input_to_hidden_weight_gradients = \
                                    v_rectified_linear_unit_derivative(hidden_layer_error) * \
                                    input_values# TODO

# Use gradients to adjust weights and biases using gradient descent
biases = biases - bias_gradients # TODO
input_to_hidden_weights = input_to_hidden_weights - input_to_hidden_weight_gradients# TODO
hidden_to_output_weights = hidden_to_output_weights - hidden_to_output_weight_gradients# TODO

[[9.]] [[9.]]
output_layer_erro =  [[-1.]]
hidden_layer_error =  [[0 0 0]]
hidden_to_output_weight_gradients =  [[-3.]
 [-3.]
 [-3.]]


ValueError: shapes (1,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
x1 =2
x2 = 1
y = 10
temp1 = np.matrix([[x1],[x2]])
hidden_layer_weighted_input = np.matmul(input_to_hidden_weights, temp1)
v_rectified_linear_unit = np.vectorize(rectified_linear_unit)
hidden_layer_activation = v_rectified_linear_unit(hidden_layer_weighted_input)

output = np.matmul(hidden_to_output_weights, hidden_layer_activation)
v_output_layer_activation = np.vectorize(output_layer_activation)
activated_output = v_output_layer_activation(output)

In [15]:
output_layer_error = 0.5 * (y-activated_output)**2
output_layer_error, activated_output

(matrix([[0.5]]), matrix([[9.]]))

In [22]:
n1 = np.exp(1)
n1/(1+n1)**2

0.19661193324148185

In [ ]:
def train(self, x1, x2, y):

        ### Forward propagation ###
    input_values = np.matrix([[x1],[x2]]) # 2 by 1

        # Calculate the input and activation of the hidden layer
    hidden_layer_weighted_input = # TODO (3 by 1 matrix)
    hidden_layer_activation = # TODO (3 by 1 matrix)

    output =  # TODO
    activated_output = # TODO

        ### Backpropagation ###

        # Compute gradients
    output_layer_error = # TODO
    hidden_layer_error = # TODO (3 by 1 matrix)

    bias_gradients = # TODO
    hidden_to_output_weight_gradients = # TODO
    input_to_hidden_weight_gradients = # TODO

        # Use gradients to adjust weights and biases using gradient descent
    biases = # TODO
    input_to_hidden_weights = # TODO
    hidden_to_output_weights = # TODO