In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import torch

In [3]:
some_ones = torch.ones(2,2)
some_zeroes = torch.zeros(2,2)
some_normals = torch.randn(2,2)
print(some_ones, some_zeroes, some_normals)

tensor([[1., 1.],
        [1., 1.]]) tensor([[0., 0.],
        [0., 0.]]) tensor([[-0.5415,  2.5487],
        [ 1.2246, -0.5551]])


In [6]:
torch_tensor = torch.randn(5,5)
numpy_ndarray = torch_tensor.numpy()
back_to_torch = torch.from_numpy(numpy_ndarray)

In [9]:
type(torch_tensor.numpy())

numpy.ndarray

In [14]:
a = torch.randn(5,5)
b = torch.randn(5,5)
a,b

(tensor([[-0.3601, -0.2345, -1.5063, -0.8409, -1.1991],
         [ 1.9193, -1.8202, -0.2340,  0.8220,  0.7704],
         [ 0.0796,  1.0499,  0.5218, -0.1456,  0.6583],
         [-1.0532, -0.0729,  1.1972, -0.3562, -0.4382],
         [ 0.8485, -2.4902, -0.0214, -0.6221, -1.1294]]),
 tensor([[-2.0512, -1.0785, -0.4228,  1.0974,  0.8253],
         [ 0.0765, -1.1535, -0.3433,  0.6884,  0.4030],
         [ 0.2999, -0.3668,  1.5478, -0.1636,  0.4631],
         [ 0.8547, -1.8820,  1.7084,  0.1771,  1.0310],
         [ 1.5566, -1.3181, -1.0052, -2.2593, -0.1423]]))

In [13]:
another_tensor = a[2,2]
print(type(another_tensor), another_tensor)
print(another_tensor.item(), type(another_tensor.item()))

<class 'torch.Tensor'> tensor(1.1231)
1.1231378316879272 <class 'float'>


In [12]:
another_tensor.item()

1.1231378316879272

In [17]:
a.size()
vec = a[:, 0]
type(vec), vec.size()

(torch.Tensor, torch.Size([5]))

In [21]:
a = torch.randn(5,5)
c = a.unsqueeze(-1)
print(c.size(), c)
print(a)

torch.Size([5, 5, 1]) tensor([[[ 0.0895],
         [-1.1531],
         [-0.9727],
         [ 0.7211],
         [ 1.3283]],

        [[-0.8284],
         [-0.2210],
         [ 1.0579],
         [-1.7494],
         [-0.2265]],

        [[ 2.1874],
         [-0.4496],
         [-0.5500],
         [-0.5801],
         [-0.9413]],

        [[-0.0610],
         [ 0.9735],
         [ 1.3902],
         [-0.5973],
         [-0.6216]],

        [[-1.4979],
         [-0.9160],
         [-0.6361],
         [-0.1373],
         [-1.2881]]])
tensor([[ 0.0895, -1.1531, -0.9727,  0.7211,  1.3283],
        [-0.8284, -0.2210,  1.0579, -1.7494, -0.2265],
        [ 2.1874, -0.4496, -0.5500, -0.5801, -0.9413],
        [-0.0610,  0.9735,  1.3902, -0.5973, -0.6216],
        [-1.4979, -0.9160, -0.6361, -0.1373, -1.2881]])


In [22]:
print(c[0,:,:])

tensor([[ 0.0895],
        [-1.1531],
        [-0.9727],
        [ 0.7211],
        [ 1.3283]])


In [24]:
a = torch.randn(2)
print(a)
a = a.unsqueeze(-1)
print(a)

tensor([0.6015, 1.1829])
tensor([[0.6015],
        [1.1829]])


In [26]:
torch.cuda.is_available()

False

In [29]:
a = torch.randn(5,3,3)
b = torch.randn(5,3,3)
print(a, a[0,:,:])

tensor([[[ 1.0078, -1.3015, -0.4700],
         [-0.9522,  1.8640, -0.8614],
         [ 0.4220, -0.0699,  0.6447]],

        [[-0.4952,  0.2860, -1.1545],
         [-0.7308,  0.8890,  1.1448],
         [-0.6233, -1.9111, -0.2429]],

        [[-0.3349,  0.3769, -0.6323],
         [-2.5318, -1.0494, -1.5568],
         [ 0.6579, -0.8559,  2.1077]],

        [[ 0.2556,  0.1497,  1.2563],
         [ 1.5986,  1.3587,  0.9619],
         [ 1.4416,  1.1394,  1.6302]],

        [[ 0.4797, -0.2428, -1.1404],
         [ 0.4507,  1.3840, -2.1882],
         [ 0.7480,  0.1702,  0.5002]]]) tensor([[ 1.0078, -1.3015, -0.4700],
        [-0.9522,  1.8640, -0.8614],
        [ 0.4220, -0.0699,  0.6447]])


In [30]:
x = torch.randn(1, requires_grad=True)
print(x)

tensor([0.2120], requires_grad=True)


In [31]:
print(x.grad)

None


In [32]:
y = x.exp()
y

tensor([1.2361], grad_fn=<ExpBackward>)

In [34]:
y.backward()

In [35]:
print(x.grad,y)

tensor([1.2361]) tensor([1.2361], grad_fn=<ExpBackward>)


In [38]:
x1 = torch.randn(2, requires_grad=True)
print(x1)
y = x1.exp()
print(y)
y[0].backward()
print(x.grad,y)

tensor([0.8922, 2.0349], requires_grad=True)
tensor([2.4405, 7.6512], grad_fn=<ExpBackward>)
tensor([1.2361]) tensor([2.4405, 7.6512], grad_fn=<ExpBackward>)


In [43]:
x_a = torch.randn(1, requires_grad=True)
x_b = torch.randn(1, requires_grad=True)
print(x_a, x_b)
x = x_a * x_b
x1 = x**2
x2 = 1/x1
x3 = x2.exp()
x4 = 1 + x3
x5 = x4.log()
x6 = x5 ** (1/3)
x2.backward()
print(x_a.grad, x_b.grad)
print(-2/x**3)

tensor([-0.3080], requires_grad=True) tensor([-0.6138], requires_grad=True)
tensor([181.6817]) tensor([91.1586])
tensor([-295.9779], grad_fn=<MulBackward0>)


In [44]:
x_a = torch.randn(1, requires_grad=True)
x_b = torch.randn(1, requires_grad=True)
print(x_a, x_b)
x = x_a * x_b
print(x)
x.backward()
print(x_a.grad, x_b.grad)

tensor([1.2212], requires_grad=True) tensor([-1.7901], requires_grad=True)
tensor([-2.1861], grad_fn=<MulBackward0>)
tensor([-1.7901]) tensor([1.2212])


In [45]:
from sklearn.datasets import make_classification

In [49]:
#help(make_classification)

In [47]:
import torch.nn as nn

In [50]:
#help(nn.Sequential)

In [51]:
model = nn.Sequential(
            nn.Linear(784,10),
            nn.LeakyReLU(),
            nn.Linear(10,10))