In [1]:
import numpy as np

In [2]:
A = np.random.rand(3,2)
A

array([[0.33211359, 0.66001639],
       [0.88630441, 0.23533342],
       [0.14837889, 0.59192186]])

In [3]:
?np.random.rand

In [4]:
B = np.random.rand(3,2)
A, B

(array([[0.33211359, 0.66001639],
        [0.88630441, 0.23533342],
        [0.14837889, 0.59192186]]), array([[0.48134902, 0.40339921],
        [0.42995258, 0.58077471],
        [0.03509859, 0.61125903]]))

In [5]:
s = np.linalg.norm(A+B)
s

2.381690019405744

In [6]:
A = np.random.random([2,1])
B = np.random.random([2,1])
C = np.matmul(A.transpose(), B)
C

array([[0.17981599]])

In [7]:
weights = np.array( [[0.9690102], [0.34224317]])
inputs = np.array([[0.8787116],[0.81064099]])
t1 = np.matmul(weights.transpose(), inputs)
z = np.tanh(t1)
z

array([[0.81064823]])

In [8]:
x = 5
y = 6
def scalar_function(x, y):
    if x <=y :
        return x*y
    else:
        return x/y
    
scalar_function(x, y)

30

In [9]:
A, B

(array([[0.40252258],
        [0.50621438]]), array([[0.17266952],
        [0.21791679]]))

In [10]:
vscalar = np.vectorize(scalar_function)
vscalar(A, B)

array([[2.33117336],
       [2.32297098]])

In [11]:
a1 = np.array([1,-1,2,-3])
theta = np.array([1,-1,2,-3])
#np.dot(a, theta)

In [12]:
a2 = np.array([1,2,3,4])
a3=np.array([-1,-1,-1,-1])
a4 = np.array([1,1,1,1])
a = [a1, a2, a3, a4]
for i in a:
    print(i)
    print(np.dot(i, theta))

[ 1 -1  2 -3]
15
[1 2 3 4]
-7
[-1 -1 -1 -1]
1
[1 1 1 1]
-1


In [13]:
?np.concatenate

In [14]:
def percept(X, Y):
    T = 50
    theta = np.zeros(X.shape[1])
    th0 = 0
    num_mistake = 0
    for t in range(T):
        for i in range(len(Y)):
            if Y[i] * (np.dot(theta, X[i]) + th0) <= 0:
                print(X[i])
                print(Y[i] * (np.dot(theta, X[i]) + th0))
                theta = theta + Y[i] * X[i]
                #th0 = th0 + Y[i]
                num_mistake += 1
                #print('new theta')
                #print(theta)
    return (num_mistake, theta, th0)

In [15]:
x = np.array([[1,-1],[0,1],[-1.5,-1]])
y = np.array([1,-1,1])
num_mistake, theta, th0 = percept(x, y)
print(num_mistake, theta, th0)

[ 1. -1.]
0.0
[-1.5 -1. ]
-0.5
2 [-0.5 -2. ] 0


In [16]:
xx = x.copy()
xx[0] = x[1]
xx[1] = x[2]
xx[2] = x[0]
yy = y.copy()
yy[0] = y[1]
yy[1] = y[2]
yy[2] = y[0]
print(xx, yy)

[[ 0.   1. ]
 [-1.5 -1. ]
 [ 1.  -1. ]] [-1  1  1]


In [17]:
num_mistake, theta, th0 = percept(xx, yy)
print(num_mistake, theta, th0)

[0. 1.]
-0.0
1 [ 0. -1.] 0


In [18]:
a = np.array([[0,1],[-10, -1],[1,-1]])
b = np.array([-1,1, 1])
num_mistake, theta, th0 = percept(a, b)
print(num_mistake, theta, th0)

[0 1]
-0.0
1 [ 0. -1.] 0


In [19]:
print(x, y)
num_mistake, theta, th0 = percept(x, y)
print(num_mistake, theta, th0)

[[ 1.  -1. ]
 [ 0.   1. ]
 [-1.5 -1. ]] [ 1 -1  1]
[ 1. -1.]
0.0
[-1.5 -1. ]
-0.5
2 [-0.5 -2. ] 0


In [20]:
a = np.array([[-3,2],[-1,1], [-1,-1],[2,2],[1,-1]])
b = np.array([1,-1,-1,-1,-1])
print(a, b)

[[-3  2]
 [-1  1]
 [-1 -1]
 [ 2  2]
 [ 1 -1]] [ 1 -1 -1 -1 -1]


In [21]:
num_mistake, theta, th0 = percept(a, b)
print(num_mistake, theta, th0)

[-3  2]
0.0
[-1  1]
-5.0
[-1 -1]
-1.0
[2 2]
-2.0
[-1  1]
-3.0
[-1 -1]
-3.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-3.0
[ 1 -1]
-1.0
[-1  1]
-1.0
[-1 -1]
-1.0
[2 2]
-2.

In [22]:
a = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
b = np.array([-1,-1,-1,-1,-1,-1,-1,1])
print(a, b)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]] [-1 -1 -1 -1 -1 -1 -1  1]


In [23]:
num_mistake, theta, th0 = percept(a, b)
print(num_mistake, theta, th0)

[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0
[0 1 0]
-0.0
[1 0 0]
-0.0
[1 1 1]
-3.0
[0 0 0]
-0.0
[0 0 1]
-0.0

In [24]:
a = np.array([[-1,1],[1, -1], [1,1],[2,2]])
b = np.array([1,1,-1,-1])
print(a,b)

[[-1  1]
 [ 1 -1]
 [ 1  1]
 [ 2  2]] [ 1  1 -1 -1]


In [25]:
num_mistake, theta, th0 = percept(a, b)
print(num_mistake, theta, th0)

[-1  1]
0.0
[ 1 -1]
-2.0
[1 1]
-0.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 1 -1]
-2.0
[-1  1]
0.0
[ 

In [26]:
a = np.array([[1,-1,1],[1,1,1], [2,-1,1], [2,1,1]])
b = np.array([1,1,-1,-1])
print(a,b)
a.shape

[[ 1 -1  1]
 [ 1  1  1]
 [ 2 -1  1]
 [ 2  1  1]] [ 1  1 -1 -1]


(4, 3)

In [27]:
num_mistake, theta, th0 = percept(a, b)
print(num_mistake, theta, th0)

[ 1 -1  1]
0.0
[ 2 -1  1]
-4.0
[ 1 -1  1]
-1.0
[1 1 1]
0.0
[ 2 -1  1]
-4.0
[2 1 1]
-0.0
[ 1 -1  1]
-3.0
[1 1 1]
-2.0
[ 2 -1  1]
-0.0
[ 1 -1  1]
-3.0
[1 1 1]
0.0
[ 2 -1  1]
-0.0
[ 1 -1  1]
-3.0
[2 1 1]
-0.0
[ 1 -1  1]
-2.0
[1 1 1]
-1.0
[ 2 -1  1]
-0.0
[ 1 -1  1]
-2.0
18 [-3.  0.  4.] 0


In [28]:
aa = a[:, 0:2]
bb = b
num_mistake, theta, th0 = percept(aa, bb)
print(num_mistake, theta, th0)

[ 1 -1]
0.0
[1 1]
0.0
[ 2 -1]
-4.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]
-2.0
[ 2 -1]
-0.0
[ 1 -1]
-3.0
[1 1]
-1.0
[2 1]
-1.0
[ 1 -1]
-2.0
[1 1]

In [29]:
R = 1
n = 1000
k_list = []
gamma_list = np.array([0.00001, 0.0001, 0.001, 0.01, 0.1, 0.2, 0.5])
for gamma in gamma_list:
    k_list.append((R/gamma)**2)
print(k_list)

[9999999999.999996, 100000000.0, 1000000.0, 10000.0, 100.0, 25.0, 4.0]


In [30]:
a = np.arange(32).reshape((4,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [31]:
b = np.array(range(8))
c = np.array_split(b, 4)
c
print(c[0], c[1], c[2])
d = np.concatenate((c[0], c[2]), axis=None)
e = a[:, d]
e

[0 1] [2 3] [4 5]


array([[ 0,  1,  4,  5],
       [ 8,  9, 12, 13],
       [16, 17, 20, 21],
       [24, 25, 28, 29]])

In [32]:
d = np.concatenate((c[0], c[2]), axis=None)

In [33]:
np.concatenate((d, c[3]))

array([0, 1, 4, 5, 6, 7])

In [34]:
f = np.delete(b, c[1])
f

array([0, 1, 4, 5, 6, 7])

In [35]:
b

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
def percept1(X, Y):
    T = 1000
    theta = np.zeros(X.shape[1])
    th0 = 0
    #theta = np.array([0, 1, -0.5])
    theta = np.array([0, 0, 0])
    num_mistake = 0
    for t in range(T):
        for i in range(len(Y)):
            if Y[i] * (np.dot(theta, X[i])) <= 0:
                #print(X[i])
                #print(Y[i] * (np.dot(theta, X[i]) + th0))
                theta = theta + Y[i] * X[i]
                th0 = th0 + Y[i]
                num_mistake += 1
                #print('new theta')
                #print(theta)
    return (num_mistake, theta, th0)

In [37]:
data = np.array([[200,800,200,800], [0.2,0.2, 0.8, 0.8], [1, 1, 1, 1]])
labels = np.array([-1, -1, 1, 1])


In [38]:
data1 = data.T
data1[0]

array([200. ,   0.2,   1. ])

In [39]:
def find_gamma(X, Y):
    N = len(Y)
    gamma = 100000
    norm = np.sqrt(np.dot(theta, theta))
    for i in range(N):
        dist = Y[i] * (np.dot(theta, X[i])) / norm
        if dist < gamma:
            gamma = dist
    return gamma

In [40]:
theta = np.array([0, 1, -0.5])

In [41]:
find_gamma(data1, labels)

0.2683281572999747

In [42]:
np.sqrt(1+0.25)

1.118033988749895

In [43]:
def find_R(X):
    R = 0
    N = X.shape[1]
    for i in range(N):
        dist = np.sqrt(sum(X[:,i]**2))
        if dist > R:
            R = dist
    return R

In [44]:
(find_R(data)/find_gamma(data1, labels))**2

8888911.666666672

In [45]:
num_mistake, th, t0 = percept1(data1, labels)
print(num_mistake, th, t0)

2000 [  0. 600.   0.] 0


In [46]:
labels[0] * (np.dot(theta, data1[0]))

0.3

In [47]:
len(labels)

4

In [48]:
data2 = data1[:, 0:2]
data2 = data2 * 0.001
data4 = np.array([[1, 1, 1, 1]])
data3 = np.concatenate((data2, data4.T), axis=1)
data3

array([[2.e-01, 2.e-04, 1.e+00],
       [8.e-01, 2.e-04, 1.e+00],
       [2.e-01, 8.e-04, 1.e+00],
       [8.e-01, 8.e-04, 1.e+00]])

In [49]:
find_gamma(data3, labels)

-0.44649805374715795

In [50]:
find_R(data3.T)

1.2806250973645645

In [51]:
(find_R(data3.T)/find_gamma(data3, labels))**2

8.226306320882646

In [52]:
data = np.array([[200,800,200,800], [0.2,0.2, 0.8, 0.8], [1, 1, 1, 1]])
labels = np.array([-1, -1, 1, 1])
data1 = np.copy(data)
data1[0 ] = data1[0] * 0.001
data1

array([[0.2, 0.8, 0.2, 0.8],
       [0.2, 0.2, 0.8, 0.8],
       [1. , 1. , 1. , 1. ]])

In [53]:
theta = np.array([0, 1, -0.5])
theta

array([ 0. ,  1. , -0.5])

In [54]:
find_gamma(data1.T, labels)

0.2683281572999747

In [55]:
(find_R(data1)/find_gamma(data1.T, labels)) ** 2

31.666666666666686

In [56]:
num_mistake, th, t0 = percept1(data1.T, labels)
print(num_mistake, th, t0)

7 [-0.2  1.6 -1. ] -1


In [57]:
data = np.array([[2,3,4,5]])
data1 = data.T
print(data1)
labels = np.array([1,1,-1,-1])

[[2]
 [3]
 [4]
 [5]]


In [58]:
def percept2(X, Y):
    T = 1000
    theta = np.zeros(X.shape[1])
    th0 = 0
    #theta = np.array([0, 1, -0.5])
    #theta = np.array([0, 0, 0])
    num_mistake = 0
    for t in range(T):
        for i in range(len(Y)):
            if Y[i] * (np.dot(theta, X[i])) <= 0:
                #print(X[i])
                #print(Y[i] * (np.dot(theta, X[i]) + th0))
                theta = theta + Y[i] * X[i]
                th0 = th0 + Y[i]
                num_mistake += 1
                #print('new theta')
                #print(theta)
    return (num_mistake, theta, th0)

In [59]:
num_mistake, theta, th0 = percept2(data1, labels)

In [60]:
print(num_mistake, theta, th0)

2666 [-2.] 666


In [61]:
np.zeros((7,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [62]:
def one_hot(x, k):
    value = np.zeros((k, 1))
    value[x-1] = 1
    return value

In [63]:
one_hot(3, 7)

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [64]:
group = 6
data = np.array([[2,3,4,5]])
labels = np.array([[1, 1, -1, -1]])

In [65]:
d = group
N = data.shape[1]
ans = np.zeros((d, N))
ans

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
def feature_one_hot(data, group):
    N = data.shape[1]
    ans = np.zeros((group, N))
    for i in range(N):
        val = one_hot(data[:, i], group)
        ans[:, i] = val.reshape(group)
    print(ans)
    return ans

In [67]:
data3 = np.array([[1, 6]])
res = feature_one_hot(data3, 6)


[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [68]:
res = np.array([[1, 0,0,0,0,0,1], [0,0,0,0,0,1,1]])
theta = np.array([0,2,1,-2,-1,0,0])
label = np.array([-1, -1])
find_gamma(res,label)

0.0

In [69]:
norm = np.sqrt(np.dot(theta, theta))
print(norm)
dist = np.dot(theta, res[1])/norm
print(dist)

3.1622776601683795
0.0


In [70]:
data1 = np.array([1,2])
data2 = np.array([2,3])
data3 = np.array([3,4])
data_list = {1:data1, 2:data2, 3:data3}
for i in data_list.keys():
    print(i)
    print(data_list[i])

1
[1 2]
2
[2 3]
3
[3 4]


In [71]:
a = np.array([2,5,7, 20, 30, 15, 9, 28])
b = np.argsort(a)
b

array([0, 1, 2, 6, 5, 3, 7, 4])

In [72]:
def row_average_features(x):
    """
    @param x (m,n) array with values in (0,1)
    @return (m,1) array where each entry is the average of a row
    """
    row_sum = np.sum(x, axis=1)
    d,n = x.shape
    return (row_sum/n).reshape((d, 1))

In [73]:
a = np.array([[1,2,3],[3,9,2]])
row_average_features(a)

array([[2.        ],
       [4.66666667]])

In [74]:
def col_average_features(x):
    """
    This should either use or modify your code from the tutor questions.

    @param x (n_samples,m,n) array with values in (0,1)
    @return (n,n_samples) array where each entry is the average of a column
    """
    col_sum = np.sum(x, axis=0)
    d,n = x.shape
    return (col_sum/d).reshape((n, 1))

In [75]:
col_average_features(a)

array([[2. ],
       [5.5],
       [2.5]])

In [101]:
def top_bottom_features(x):
    _,m, n = x.shape
    top_image = x[:,0:m//2, :]
    bot_image = x[:,m//2:, :]
    top_avg = np.mean(top_image, axis=(1,2))
    bot_avg = np.mean(bot_image, axis=(1,2))
    return np.array([top_avg, bot_avg])

In [77]:
a = np.array([[1,2,3], [3,9,2], [2,1,9]])
top_bottom_features(a)

array([[2.        ],
       [4.33333333]])

In [78]:
A = np.array([
   [[ 1,  2,  3],[ 4,  5,  6], [12, 34, 90]],
   [[ 4,  5,  6],[ 2,  5,  6], [ 7,  3,  4]]
])
A

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [12, 34, 90]],

       [[ 4,  5,  6],
        [ 2,  5,  6],
        [ 7,  3,  4]]])

In [84]:
np.sum(A, axis=0)

array([[ 5,  7,  9],
       [ 6, 10, 12],
       [19, 37, 94]])

In [94]:
np.sum(A, axis=(1,2))

array([157,  42])

In [81]:
A.shape

(2, 3, 3)

In [102]:
tp, bt = top_bottom_features(A)
print(tp, bt)

[2. 5.] [25.16666667  4.5       ]


In [87]:
B = np.array(
   [[ 1,  2,  3],[ 4,  5,  6], [12, 34, 90]])

In [89]:
print(B)
print(np.sum(B, axis=0))
print(np.sum(B, axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [12 34 90]]
[17 41 99]
[  6  15 136]


In [106]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.vstack((c,d))

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
?np.vstack