In [1]:
import numpy as np

In [7]:
A = np.random.rand(3,2)
A

array([[0.22290823, 0.69062483],
       [0.31775312, 0.21606975],
       [0.69973601, 0.99904537]])

In [6]:
?np.random.rand

In [8]:
B = np.random.rand(3,2)
A, B

(array([[0.22290823, 0.69062483],
        [0.31775312, 0.21606975],
        [0.69973601, 0.99904537]]), array([[0.30851103, 0.73396036],
        [0.22286659, 0.61749273],
        [0.56959118, 0.55246238]]))

In [9]:
s = np.linalg.norm(A+B)
s

2.705053296701276

In [14]:
A = np.random.random([2,1])
B = np.random.random([2,1])
C = np.matmul(A.transpose(), B)
C

array([[0.24677478]])

In [17]:
weights = np.array( [[0.9690102], [0.34224317]])
inputs = np.array([[0.8787116],[0.81064099]])
t1 = np.matmul(weights.transpose(), inputs)
z = np.tanh(t1)
z

array([[0.81064823]])

In [20]:
x = 5
y = 6
def scalar_function(x, y):
    if x <=y :
        return x*y
    else:
        return x/y
    
scalar_function(x, y)

30

In [22]:
A, B

(array([[0.73742836],
        [0.09061573]]), array([[0.2940082 ],
        [0.33067983]]))

In [23]:
vscalar = np.vectorize(scalar_function)
vscalar(A, B)

array([[2.50818976],
       [0.02996479]])